export const fetchAnswerResponse = (userId: number) => {
    console.log(`[Mocks] fetchAnswerResponse : ${userId}`);
    return [
        {
            questionId: 1,
            questionText: "기상시간",
            questionType: "doubleSlider",
            options: [
                { label: "min", value: "7" },
                { label: "max", value: "9" },
                { label: "unit", value: "시" },
            ],
            dataType: "string",
        },
        {
            questionId: 2,
            questionText: "취침시간",
            questionType: "doubleSlider",
            options: [
                { label: "min", value: "23" },
                { label: "max", value: "25" },
                { label: "unit", value: "시" },
            ],
            dataType: "string",
        },
        {
            questionId: 3,
            questionText: "잠귀",
            questionType: "slider",
            options: [{ label: "value", value: "3" }],
            dataType: "string",
        },
        {
            questionId: 4,
            questionText: "취침등",
            questionType: "selector",
            options: [{ label: "없음", value: "없음" }],
            dataType: "string",
        },
        {
            questionId: 5,
            questionText: "알람 설정",
            questionType: "selector",
            options: [{ label: "없음", value: "없음" }],
            dataType: "string",
        },
        {
            questionId: 6,
            questionText: "잠버릇",
            questionType: "checkbox",
            options: [
                { label: "코골이", value: "코골이" },
                { label: "잠꼬대", value: "잠꼬대" },
            ],
            dataType: "string",
        },
        {
            questionId: 7,
            questionText: "더위",
            questionType: "slider",
            options: [{ label: "value", value: "3" }],
            dataType: "string",
        },
        {
            questionId: 8,
            questionText: "추위",
            questionType: "slider",
            options: [{ label: "value", value: "3" }],
            dataType: "string",
        },
        {
            questionId: 9,
            questionText: "청소주기",
            questionType: "selector",
            options: [{ label: "매일", value: "매일" }],
            dataType: "string",
        },
        {
            questionId: 11,
            questionText: "취침등",
            questionType: "selector",
            options: [{ label: "스탠드", value: "스탠드" }],
            dataType: "string",
        },
        {
            questionId: 12,
            questionText: "룸메이트와 관계",
            questionType: "slider",
            options: [{ label: "value", value: "3" }],
            dataType: "string",
        },
        {
            questionId: 13,
            questionText: "룸메이트와 물건공유",
            questionType: "selector",
            options: [{ label: "없음", value: "없음" }],
            dataType: "string",
        },
        {
            questionId: 14,
            questionText: "친구초대",
            questionType: "selector",
            options: [{ label: "스탠드", value: "스탠드" }],
            dataType: "string",
        },
        {
            questionId: 15,
            questionText: "본가방문 주기",
            questionType: "selector",
            options: [{ label: "없음", value: "없음" }],
            dataType: "string",
        },
        {
            questionId: 16,
            questionText: "공부장소",
            questionType: "selector",
            options: [{ label: "없음", value: "없음" }],
            dataType: "string",
        },
        {
            questionId: 17,
            questionText: "운동빈도",
            questionType: "selector",
            options: [{ label: "안함", value: "안함" }],
            dataType: "string",
        },
        {
            questionId: 18,
            questionText: "운동시간대",
            questionType: "selector",
            options: [{ label: "아침", value: "아침" }],
            dataType: "string",
        },
        {
            questionId: 19,
            questionText: "게임",
            questionType: "selector",
            options: [{ label: "안함", value: "안함" }],
            dataType: "string",
        },
        {
            questionId: 20,
            questionText: "흡연",
            questionType: "selector",
            options: [{ label: "둘다", value: "둘다" }],
            dataType: "string",
        },
        {
            questionId: 21,
            questionText: "실내통화",
            questionType: "selector",
            options: [{ label: "안함", value: "안함" }],
            dataType: "string",
        },
        {
            questionId: 22,
            questionText: "음주빈도",
            questionType: "slider",
            options: [{ label: "value", value: "3" }],
            dataType: "string",
        },
    ];
};
